---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: function-cue
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
  - step: run-the-template
    functionRef:
      name: function-cue
    input:
      apiVersion: template.fn.crossplane.io/v1beta1
      kind: Input
      script: |
        package main
        composite: #request.observed.composite.resource
        response: desired: resources: {
          configMap: resource: {
            apiVersion: "v1"
            kind: "ConfigMap"
            data: compositeName: composite.metadata.name
          }
        }
